### ISSUE TITLE
more flexible user-settings

### ISSUE THREAD

**Issue by xDashh** [MemeLabs/Rustla2#98]
I think right now for each (new) user setting the backend database has to be modified. It would be nice if we just stored a json blob(?) in the db, and people could modify that easily / new settings could be added without too much trouble.

Related issues/feature-requests:
- [ ] hide streams that fit some criteria https://github.com/MemeLabs/Rustla2/issues/18 https://github.com/MemeLabs/Rustla2/issues/39
- [ ]  possible misc. UI modifications https://github.com/MemeLabs/Rustla2/issues/83
- [ ]  being able to remove warning pages like for advanced and nsfw ( https://github.com/MemeLabs/Rustla2/issues/97 ) permanently
